### ISSUE TITLE
GCC suggest-override warnings

### ISSUE THREAD

**Issue by EugeneZelenko** [boostorg/any#13]
Complete list of warnings when Boost 1.72 is built with GCC 7.5 with `-Wsuggest-override` added to `cxxflags`. Duplicated warnings from same location are omitted::

<pre>
./boost/any.hpp:190:56: warning: ‘const type_info& boost::any::holder<ValueType>::type() const [with ValueType = bool; boost::typeindex::type_info = std::type_info]’ can be marked override [-Wsuggest-override]
./boost/any.hpp:195:35: warning: ‘boost::any::placeholder* boost::any::holder<ValueType>::clone() const [with ValueType = bool]’ can be marked override [-Wsuggest-override]
./boost/any.hpp:241:30: warning: ‘virtual const char* boost::bad_any_cast::what() const’ can be marked override [-Wsuggest-override]
</pre>

`BOOST_OVERRIDE` was introduced in https://github.com/boostorg/config/commit/ffe4e0f5a448578cce14e3eed0cf7163333a81d9.

**Comment by apolukhin** [comment]
Thanks for the report!

**Comment by EugeneZelenko** [comment]
Thank you for fix!
