### ISSUE TITLE
Type casting short hand

### ISSUE THREAD

**Issue by BoredBored** [boostorg/any#16]
Please implement the below
```c++
template <typename ValueType>
constexpr operator ValueType() const {return boost::any_cast<ValueType>(*this);}
```
As it makes the code look nicer
```c++
std::string foo = "Hello World!\n";
boost::any value = foo;
std::cout << (std::string)value;
```

**Comment by apolukhin** [comment]
* Implicit casts provoke hard detectable errors.
* C-style casts `(Type)value` provoke hard detectable errors, use static_cast/dynamic_cast

Your example becomes 
```
std::string foo = "Hello World!\n";
boost::any value = foo;
std::cout << static_cast<std::string>(value);
```
Which is not better than the current approach.

Finally, adding functionality that does not exist in std::any makes the migration to the standard type much harder.

Sorry, the feature woukd not be implemented.
