### ISSUE TITLE
Add a complimentary boost::unique_any

### ISSUE THREAD

**Issue by gloinart** [boostorg/any#24]
Add a variant of boost::any which accepts move-only object such as std::unique_ptr (and therefore, the boost::any is move-only itself)

**Comment by apolukhin** [comment]
It is implemented for quite some time https://github.com/boostorg/any/blob/develop/include/boost/any/unique_any.hpp

However, I had no time to write tests and update docs on it. PR are welcome

**Comment by apolukhin** [comment]
Looks like done

Should be shipped in Boost 1.83

**Comment by gloinart** [comment]
Hi Antony,

Sounds great, looking forward to using it!

Best/Viktor

**Comment by gloinart** [comment]
Hi,

A note on unique_any. In difference to boost::any it seems to miss the
"empty()" member function and contains "has_value()" instead.
Although this rhymes with the implementation of std::any, wouldn't it be an
idea to synchronize the interface for all the anys in boost::any?
(i.e both have has_value(), empty(), and emplace())

Best/Viktor
