### ISSUE TITLE
1.83 documentation reference links go to the reference for PFR

### ISSUE THREAD

**Issue by pdimov** [boostorg/any#27]
The reference links on

https://www.boost.org/doc/libs/1_83_0/doc/html/any.html

go to

https://www.boost.org/doc/libs/1_83_0/doc/html/reference_section.html

which is the reference for PFR, not Any.

**Comment by apolukhin** [comment]
I have no idea how it happened.

Asked for help a few months ago at mailing list "[boost] Reference section of Boost.Any leads to Boost.PFR". No response

**Comment by pdimov** [comment]
My guess is that both Any and PFR generate `reference_section.html`, so one overwrites the other.

**Comment by apolukhin** [comment]
Thanks! Fixed now
